[build]
  publish = "dist"
  command = "yarn build"

[build.environment]
  HUGO_VERSION = "0.146.5"
  NODE_VERSION = "16" # Node 12は古いので16〜18を推奨
  YARN_VERSION = "1.22.19" # 最新のYarn 1.x系に更新

[context.deploy-preview]
  command = "yarn build-preview"
