baseurl = "/"
languageCode = "en-us"
title = "IEEE Haptics Symposium 2020"
logo = "/img/hs-logo.png"
copyright = "IEEE Haptics Symposium 2020. Theme adapted from Netlify CMS."

[params]
    conferenceDate = "March 28 - 31, 2020"
    conferenceLocation = "Washington, DC"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true